### ISSUE TITLE
Trouble setting array from variable

### ISSUE THREAD

**Issue by github-rage** [Fr0sT-Brutal/TemplateEngine#1]
Hey,

Sorry for writing to a project that was not updated in 4 years. I needed a template engine and decided with yours, I really like your additions. My only problem is that when I call SetVariable with a hardcoded array, it compiles the output as expected, however, when I pass it an array variable, it does not.

`.SetVariable('arr', ['A', 'B', 'C']); // OK`

```
var Data := ['A', 'B', 'C'];
.SetVariable('arr', Data); // EVariantTypeCastError: Invalid variant type conversion
```

```
var Data := TStringDynArray.Create('A', 'B', 'C');
.SetVariable('arr', Data); // No error, but doesn't loop through the array elements in the template
```

What am I missing? How should this be done? I'm experimenting on Delphi 10.3 at the moment.

Thank you if you find the time to take a look at this!

**Comment by github-rage** [comment]
As usual, right after I submitted my question, I came up with a workaround looking at the demo project.

```
function ArrayToVariableRecord ( Input : TStringDynArray ) : TVariableRecord;
begin
  Result.SetArrayLength(Length(Input));
  for var i:=0 to High(Input) do
    Result.SetArrayItemQ(i, 'str', Input[i]);
end;

.SetVariable('errors', ArrayToVariableRecord(MyArray));
```

Still I feel this is not how it is intended to work :)

**Comment by Fr0sT-Brutal** [comment]
> Sorry for writing to a project that was not updated in 4 years

No problem here, the code doesn't have "best before" time :)
Actually the `SetArrayLength-for SetArrayItemQ` is the right way to do. Reasons why there's no such helper functions in the unit:
- Variable arrays are not so often being added to template as is
- Engine accepts several value types so several overloaded functions are needed

But feel free to create PR ;) In fact, I suppose new methods could be added to TVariableRecord as implicit operators to get rid of separate Arr/Map functions

**Comment by github-rage** [comment]
In case you don't have anything better to spend your time on, I'd be happy to see any improvements you see fit :)

I really like the flexibility of the smarty engine on php, and I'm glad there's a Delphi implementation existing - even if it's missing a few things, like regular for loops (to loop through one, and link different arrays' matching index elements into a table as separate row columns, for example), or doing a foreach on an elements subelement's subelement ( eg: foreach from=$report.stats.maxvalues item=max ), which didn't seem to work for me.

I categorize these as a matter of visualization and would try to implement them in the template instead of the project code, but I'm defnitely not qualified to modify the template engine on a level of depth like that :)

And I guess as long as the same output can be done with the SetArray methods and some internal data preparation to match the engine's requirements, what matters the most is the outcome.

**Comment by Fr0sT-Brutal** [comment]
I guess `Arr` and overloaded `Item` does what's needed, so closing this
